### ISSUE TITLE
Working example with ES256

### ISSUE THREAD

**Issue by alexbredy** [siemensikkema/vapor-jwt#10]
Hi Siemen, very nice library.
Do you have by any chance a working example with a ES256 signing?
I tried reproducing your steps below with secp521r1 in the keys generation and built the JWT with the private one and verified the signature with the public key. Unfortunately I get a `(VaporJWT.JWTError error 1.)`

This is my implementation:

        
        guard let privateKey = drop.config["keys","jwtPrivateKey"]?.string else{
            throw Abort.custom(status: .badRequest, message: "The private key is not set")
        }
        
        guard let publicKey = drop.config["keys","jwtPublicKey"]?.string else{
            throw Abort.custom(status: .badRequest, message: "The public key is not set")
        }
        
        do {
            let jwt = try JWT(payload: Node(ExpirationTimeClaim(Date() + 3600)),
                              signer: ES256(key: publicKey))
            let token = try jwt.createToken()
            print(token)
        } catch{
            print(error.localizedDescription)
        }
        
        do {
            let jwt = try JWT(token: bearer.string)
            let isValid = try jwt.verifySignatureWith(ES256(key: privateKey))
            print(isValid)
            print(bearer)
        } catch {
            print(error.localizedDescription)
        }`

Any insight on that? Thanks  a lot.

PS: The example works correctly if I use a HS256 signature.

**Comment by BrettRToomey** [comment]
The README says: `The ECDSA and RSA (ES*/RS*) signers on the other hand take a **private key** for signing and a matching **public key** for verifying.`

It looks like you have your order backward. You're signing with a public key and verifying with the private.

**Comment by alexbredy** [comment]
Thanks @BrettRToomey  for your answer. You are right. I've actually tried it both ways just to check if the docs weren't correct. I created new keys (see below) but still can't get it to work (error 1).

This is the secrets config in Vapor:
```
{
    "jwtPublicKey": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAER5wRCKw7wCTjaQ7/FTmMRFhl3+Rg4a29qkrL0QsxOIc6Ae/nWYU3CifATMvHBxcCQ+B8U6oP6ZB2OuK2WVtDeA==",
    "jwtPrivateKey": "MHcCAQEEICPJqF22Zd7Y2xUabq56odtrqTI3W7EWJwRTvF7ewETXoAoGCCqGSM49AwEHoUQDQgAER5wRCKw7wCTjaQ7/FTmMRFhl3+Rg4a29qkrL0QsxOIc6Ae/nWYU3CifATMvHBxcCQ+B8U6oP6ZB2OuK2WVtDeA=="
}
```
The tokens were generated as followed:
`openssl ecparam -name prime256v1 -genkey -out private.pem`

`openssl ec -in private.pem -outform der -out private.der`
`openssl base64 -in private.der -out /dev/stdout`
(Copy the private key in the config)

`openssl ec -in private.pem -outform der -pubout -out public.der`
`openssl base64 -in public.der -out /dev/stdout`
(Copy the public key in the config)
Do you see anything wrong? Thanks for your help.

**Comment by siemensikkema** [comment]
Hi @alexbredy! My apologies for taking so long.

I figured out what was going wrong. @BrettRToomey was right, you sign with a private key and check with a public key. However, there is one more thing you need to pay attention to, how to initialize the Signer. The keys you created are encoded in base64 and therefore you need to use a different initializer:

```swift
ES256(encodedKey: myKey)
```

If your key is encoded in a different way, like Base64URL, you can specify the encoding like so:

```swift
ES256(encodedKey: myKey, encoding: Base64URLEncoding())
```

**Comment by siemensikkema** [comment]
It turned out the docs contained invalid instructions. I've updated them. Thanks @alexbredy!

**Comment by RamboDonnie** [comment]
ES256(encodedKey
