### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dmcyk** [siemensikkema/vapor-jwt#15]
Hi, 
Do you have any plans for introducing specific license to this project? 
I'd like to use a part of this library in my open source project if possible, though lack of license makes it a bit unclear if I can do so, especially that I don't really want to depend on the whole package, only on the ecliptic curve algorithm implementation.

**Comment by siemensikkema** [comment]
Thanks for pointing that out. I thought I included a license from the beginning. I just added the MIT license (#16), mostly because it's what Vapor itself uses. Does that suit your need?

**Comment by dmcyk** [comment]
Sure it does, thanks!
