### ISSUE TITLE
EC key specification

### ISSUE THREAD

**Issue by a2** [siemensikkema/vapor-jwt#4]
Maybe a cursory look at the code wasn't enough, but where do I plug in my private EC key for signing the message?

**Comment by siemensikkema** [comment]
Here's an example:
```swift
let privateKey = "AK9pR9H2RdQRC+0Ge5SNiDA5Ua9ipulDmN4oG7lphhKn"
try JWT(payload: JSON(["user_id", .string("1")]), algorithm: .hs(._256(privateKey)))
```
I will update the docs to make this clearer!

**Comment by a2** [comment]
That uses an HMAC-based signature. I'm talking about ES256, for example.

**Comment by siemensikkema** [comment]
I just realized my error and saw that you beat me to it ;) simply change '.hs' to '.es' and you're using ES256!

**Comment by siemensikkema** [comment]
I have updated the README to include a table with the available options
